python:
  - "3.7"
  - pypy3

dist: bionic

node_js:
  - "10.15.0"

before_install:
  - sudo apt-get update
  - sudo apt-get install xmlsec1 libxmlsec1-dev

install:
  - sudo pip install pip
  - sudo pip install tox-travis
  - sudo pip install -r src/pybind/mgr/dashboard/requirements.txt

script:
  - ./src/pybind/mgr/dashboard/run-by-travis.sh

git:
  submodules: false
