python:
  - "3.7"

node_js:
  - "10.15.0"

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libxml2-dev

install:
  - pip install --user --upgrade pip
  - pip install --user -r src/pybind/mgr/dashboard/requirements.txt

script:
  - ./src/pybind/mgr/dashboard/run-by-travis.sh

git:
  submodules: false
